import { useState } from "react";
import type { AssessmentResult } from "../../src/learning-assessment.js";
import type { DesktopCommand } from "../core/contracts.js";
async function request<T>(command: DesktopCommand): Promise<T> { const result = await window.zhixing.invoke(command); if (!result.ok) throw new Error(result.error); return result.data as T; }
interface Attempt { id: string; dayId: string; questions: { title: string; choices: string[] }[]; }
export function AssessmentPanel({ topicId, days, results, disabled, refresh }: { topicId: string; days: { dayId: string; state: string }[]; results: AssessmentResult[]; disabled: boolean; refresh: () => Promise<void> }) {
  const started = days.filter((day) => day.state !== "未开始");
  const [day, setDay] = useState(started[0]?.dayId ?? "D01"); const [attempt, setAttempt] = useState<Attempt>(); const [answers, setAnswers] = useState<number[]>([]); const [reflection, setReflection] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <section className="assessment-panel"><h3>独立知识检查与复习</h3><p>实验材料齐全、代码测试通过和知识检查结果分别记录。检查题由课程预置，包含错误做法与边界案例；通过仅说明本次检查的范围。</p>
    <label>检查学习日<select aria-label="知识检查学习日" value={day} disabled={busy} onChange={(event) => { setDay(event.target.value); setAttempt(undefined); }}>{started.map((item) => <option key={item.dayId}>{item.dayId}</option>)}</select></label>
    <button disabled={disabled || busy || !started.length} onClick={() => { setBusy(true); setError(""); void request<Attempt>({ type: "assessment-start", topicId, dayId: day }).then((value) => { setAttempt(value); setAnswers(Array(value.questions.length).fill(-1)); }).catch((problem) => setError(problem.message)).finally(() => setBusy(false)); }}>开始独立检查</button>
    {attempt && <form onSubmit={(event) => { event.preventDefault(); setBusy(true); setError(""); void request<AssessmentResult>({ type: "assessment-submit", topicId, dayId: attempt.dayId, attemptId: attempt.id, answers, reflection }).then(async () => { setAttempt(undefined); await refresh(); }).catch((problem) => setError(problem.message)).finally(() => setBusy(false)); }}>{attempt.questions.map((question, index) => <fieldset key={index}><legend>{question.title}</legend>{question.choices.map((choice, choiceIndex) => <label key={choice}><input type="radio" name={`check-${index}`} checked={answers[index] === choiceIndex} disabled={busy} onChange={() => setAnswers(answers.map((value, position) => position === index ? choiceIndex : value))} />{choice}</label>)}</fieldset>)}<label>错因或复盘（可选）<textarea aria-label="知识检查复盘" maxLength={4000} value={reflection} onChange={(event) => setReflection(event.target.value)} /></label><button disabled={busy || answers.some((answer) => answer < 0)}>提交知识检查</button></form>}
    {results.map((result) => <div className="assessment-result" key={result.id}><strong>{result.dayId} · {result.status === "checks_passed" ? "本次检查通过" : "需要练习"} · {result.correctCount}/{result.total}</strong><p>建议复习：{new Date(result.reviewAt).toLocaleDateString()} {new Date(result.reviewAt).getTime() <= Date.now() ? "（已到期）" : ""}</p>{result.errorCauses.map((cause) => <p key={cause}>需复习的边界：{cause}</p>)}<details><summary>题目解析</summary>{result.explanations.map((text) => <p key={text}>{text}</p>)}</details></div>)}
    {error && <p role="alert" className="message-error">{error}</p>}
  </section>;
}
