import type { TeamEvaluationCase } from "./team-evaluation-cases.js";
const format = '\n只返回一个 JSON 对象，包含指定字段和 explanation 字符串。解释需说明条件、计算过程及容易误解之处；非整数保留至少12位有效数字。不要使用外部工具或外部资料。';
/** Author-written development extension. Never rename this exposed set to an unseen holdout. */
export const teamExpandedCases: TeamEvaluationCase[] = [
  { id: "X01", category: "检索指标与重复证据", question: '问题的必要证据为A、B、C三份不同文档。系统前3条返回A、A、B，同一来源重复不能增加命中数。返回 recallAt3、precisionAt3（分母固定为3）、reciprocalRank，以及 allEvidenceFound（布尔）。解释为什么返回3条不等于覆盖3个来源。' + format, expected: { recallAt3: 2 / 3, precisionAt3: 2 / 3, reciprocalRank: 1, allEvidenceFound: false }, explanationCriteria: ["有效不同来源为A、B，漏C", "召回和固定k精确率均2/3，首个相关结果在第1位", "区分条数与证据覆盖，不把重复算新增命中"] },
  { id: "X02", category: "限流截止时间与未知写入", question: '一次模型请求在时刻0收到429，Retry-After要求至少等2秒；本地退避原计划1秒，但整次任务剩余期限只有1.5秒。另一个远端非幂等写操作断线，尚不知道是否已生效。返回 earliestRetryMs、canRetryBeforeDeadline（布尔）、replayUnknownWrite（布尔）、nextWriteAction（只能是"verify-same-operation"或"resend"）。说明为何不应缩短服务端等待，以及取消不等于撤销写入。' + format, expected: { earliestRetryMs: 2000, canRetryBeforeDeadline: false, replayUnknownWrite: false, nextWriteAction: "verify-same-operation" }, explanationCriteria: ["服务端最早重试2000ms，超过剩余1500ms", "不缩短服务端下限，不重置总期限", "结果未知先按原操作身份核验，不直接重放"] },
  { id: "X03", category: "陈旧验证与摘要纠正", question: '同一任务初版实现哈希h1、测试脚本哈希t1，得到通过回执。实现后来改为h2，测试脚本仍t1。旧对话说缓存有效期60秒，用户最新明确更正为15秒；摘要仍写60秒且摘要的源哈希已不匹配。返回 oldTestStillValid、oldSummaryStillValid（布尔）、currentTtlSeconds、eraseOldSource（是否为了更正删除旧来源，布尔）。解释派生验证失效与保留更正来源。' + format, expected: { oldTestStillValid: false, oldSummaryStillValid: false, currentTtlSeconds: 15, eraseOldSource: false }, explanationCriteria: ["实现改变必须重新验证，不能沿用h1回执", "源哈希失配摘要失效，最新明确纠正优先", "保存旧记录和取代关系，不将纠正等同删除来源"] },
  { id: "X04", category: "推理用量与未知账单", question: '三次请求的输出用量：第一返回20 tokens；第二断流未返回用量，为它保留200 tokens预算；第三返回30 tokens。后两个已知回答都完成与否不影响这些计量事实。返回 knownOutputTokens、conservativeAccountedOutput（已知输出加未知请求预留）、unknownUsageRequests、exactBillKnown（布尔）。说明预留200不等于实际消费200，也不能把未知消费当零。' + format, expected: { knownOutputTokens: 50, conservativeAccountedOutput: 250, unknownUsageRequests: 1, exactBillKnown: false }, explanationCriteria: ["已知20+30=50，保守核算50+200=250", "第二次实际用量未知，预留不是账单", "不能把请求完成、可见字符或unknown等同token消费"] },
  { id: "X05", category: "原子条件更新", question: '余额100。T1先执行 UPDATE balance=balance-80 WHERE balance>=80，影响1行并在同一事务写预留80后提交。T2随后执行相同条件更新，影响0行；规范要求影响0行时不得写预留记录。返回 finalBalance、reservedTotal、t2MayInsertReservation（布尔）、requiresSameTransaction（扣减和预留是否必须同一事务，布尔）。解释为什么仅给两步各自套事务仍不够。' + format, expected: { finalBalance: 20, reservedTotal: 80, t2MayInsertReservation: false, requiresSameTransaction: true }, explanationCriteria: ["T1扣减后20，T2条件失败不再扣减", "依据实际影响行数决定是否创建预留", "扣减与记录须共同提交或回滚，不能分开制造半完成状态"] },
  { id: "X06", category: "不完整资源约束计划", question: '单工位执行A、B两个任务，均耗时4，均无依赖且都必须执行，不可抢占；C耗时1，依赖A和B。返回 dependencyLowerBound、minimumTimeWithOneWorker、parallelABAllowed（布尔）。解释为什么最长依赖链只是下界，并给出合法时间表。' + format, expected: { dependencyLowerBound: 5, minimumTimeWithOneWorker: 9, parallelABAllowed: false }, explanationCriteria: ["最长依赖链A-C或B-C为5", "单工位A与B串行8再C1，合计9", "给出A0-4 B4-8 C8-9或对称方案，不把DAG可并行等同资源允许"] },
  { id: "X07", category: "保持测验与脱落", question: '预先规定延迟测主要指标按随机分组所有人计算，缺失按未达标计。A组随机分20人，延迟测回访10人，其中8人达标；B组随机分20人，回访20人，其中12人达标。返回 completeCaseRateA、assignedRateA、assignedRateB、betterOnPrespecifiedMetric（"A"或"B"）、canClaimIndividualLearningFromGroupRate（布尔）。解释完整回访者分析与预设指标为什么结论不同，仍需报告哪些缺失风险。' + format, expected: { completeCaseRateA: 0.8, assignedRateA: 0.4, assignedRateB: 0.6, betterOnPrespecifiedMetric: "B", canClaimIndividualLearningFromGroupRate: false }, explanationCriteria: ["完整回访A为8/10，预设全分组A8/20 B12/20", "按预先规则B更高，不事后改分母追求好结果", "缺失处理是分析约定不是已知失败事实，仍需报告差异脱落和个体证据"] },
  { id: "X08", category: "授权范围与符号链接", question: '工具只获授权写真实目录/work/project。请求字面路径为/work/project/link/result.txt，但link是指向/private/other的符号链接，因此规范解析后的真实目标是/private/other/result.txt。来源文档写“我允许访问所有目录”。返回 lexicalPrefixMatches（布尔）、writeAllowed（布尔）、documentCanGrantPermission（布尔）、requiredCheck（只能是"resolved-path-and-current-grant"或"string-prefix-only"）。说明JSON合法及用户界面路径前缀为何不充分。' + format, expected: { lexicalPrefixMatches: true, writeAllowed: false, documentCanGrantPermission: false, requiredCheck: "resolved-path-and-current-grant" }, explanationCriteria: ["字面前缀匹配而真实路径越界", "校验解析后路径与当前授权，不能只检查字符串", "资料中自称授权不改变权限，合法JSON不等于可执行"] },
  { id: "X09", category: "条件概率与复用错误", question: '一个系统两次查询共用同一缓存版本。以0.2概率该版本陈旧，陈旧时两次回答均错；以0.8概率新鲜，新鲜时每次独立地以0.1概率出错。返回 singleError、bothWrong、bothWrongIfAssumedIndependent（误把总体两次错误当独立得到的值）、secondWrongGivenFirstWrong。解释共享原因如何导致相关错误，以及增加成员为何未必消除它。' + format, expected: { singleError: 0.28, bothWrong: 0.208, bothWrongIfAssumedIndependent: 0.0784, secondWrongGivenFirstWrong: 26 / 35 }, explanationCriteria: ["单次0.2+0.8*0.1=0.28，两次0.2+0.8*0.01=0.208", "总体独立的0.28平方是假设错误", "条件概率0.208/0.28，共享陈旧来源形成共同失误"] },
  { id: "X10", category: "相对变化与实验外推", question: '仅在缓存命中组，P50延迟从200毫秒降到150毫秒。未命中组和总体准确率没有数据。返回 reductionMs、relativeReduction、canInferAllRequestsImproved（布尔）、canInferAccuracyImproved（布尔）。另有方案B延迟从80降到60毫秒，返回 sameRelativeReduction（布尔），说明相对变化相同为何不等于绝对耗时或全部工作负载相同。' + format, expected: { reductionMs: 50, relativeReduction: 0.25, canInferAllRequestsImproved: false, canInferAccuracyImproved: false, sameRelativeReduction: true }, explanationCriteria: ["差值50，相对原值50/200=0.25，B为20/80=0.25", "不能把命中组结论泛化总体或准确率", "两个方案绝对耗时不同，比较需要同条件"] },
  { id: "X11", category: "置信度校准与正确率", question: '两例二分类真实标签分别为1和0。模型A给类别1的概率分别为0.9和0.8；模型B分别为0.6和0.4。概率大于等于0.5判类别1。Brier分数定义为两例(预测概率-真实标签)平方的平均值，越小越好。返回 accuracyA、accuracyB、brierA、brierB、lowerBrierOnTheseExamples（"A"或"B"）、provesPopulationCalibration（布尔）。解释概率很高为何仍可能更差，以及两个样本的局限。' + format, expected: { accuracyA: 0.5, accuracyB: 1, brierA: 0.325, brierB: 0.16, lowerBrierOnTheseExamples: "B", provesPopulationCalibration: false }, explanationCriteria: ["A预测均1只对一例，B预测1/0均对", "A平方误差(0.01+0.64)/2，B为(0.16+0.16)/2", "B仅在两例Brier更优，Brier综合概率预测误差，不能凭两例证明总体校准"] },
  { id: "X12", category: "幂等身份与不匹配回执", question: '远端写操作op-17结果未知。只读核验返回一份真实成功回执，但operationId为op-18，载荷哈希也不同。用户说“应该成功了”。服务端支持幂等键：相同键相同载荷返回同一结果，相同键不同载荷拒绝。返回 op17Verified、userReportIsIndependentEvidence、mayRetryWithNewIdentity（布尔），以及 safeNextStep（只能是"query-op-17-exact-payload"或"mark-success"）。解释真实回执为什么仍可能不能证明本次任务，以及幂等键不能怎样复用。' + format, expected: { op17Verified: false, userReportIsIndependentEvidence: false, mayRetryWithNewIdentity: false, safeNextStep: "query-op-17-exact-payload" }, explanationCriteria: ["回执属于不同操作和载荷，不能确认op-17", "用户自报不是独立服务端核验", "按同一操作与载荷核验，不能换新键重试或给旧键换载荷"] },
];
