import type { ChatMessage } from "./contracts.js";
export interface PerformanceVariant { submittedReasoning: string; inputBand: string; turnsPerSample?: number; windowTokens?: number; reserveOutputTokens?: number; model: string; reasoning: string; transport: string; samples: number; firstTokenP50?: number; inputTokens: number; outputTokens: number; cacheReadTokens: number; startupP50?: number; measuredTurns: number; requestP50?: number; firstEventP50?: number; processTailP50?: number; }
export interface ProviderPerformance { provider: "pi-codex" | "deepseek-api" | "demo"; completed: number; failed: number; interrupted: number; firstTokenP50?: number; firstTokenP95?: number; durationP50?: number; contextP50?: number; modelP50?: number; compactionP50?: number; variants: PerformanceVariant[]; }
function percentile(values: (number | undefined)[], fraction: number): number | undefined { const sorted = values.filter((value): value is number => value !== undefined && Number.isFinite(value)).sort((a, b) => a - b); return sorted.length ? sorted[Math.max(0, Math.ceil(sorted.length * fraction) - 1)] : undefined; }
/** Numeric metadata only. Demo and real providers are never combined. */
export function summarizePerformance(messages: readonly ChatMessage[]): ProviderPerformance[] {
  return (["pi-codex", "deepseek-api", "demo"] as const).map((provider) => {
    const samples = messages.filter((message) => message.role === "assistant" && message.provider === provider && message.status !== "running");
    const completed = samples.filter((message) => message.status === "completed");
    const inputBand = (message: ChatMessage) => message.usage?.inputTokens === undefined ? "未记录" : message.usage.inputTokens < 4000 ? "<4k" : message.usage.inputTokens < 16_000 ? "4k–16k" : "≥16k";
    const turnCount = (message: ChatMessage) => message.timings?.turns ?? message.modelTimings?.length;
    const reasoning = (message: ChatMessage) => [...new Set(message.modelTimings?.map(turn => turn.submittedReasoning ?? "未记录") ?? [])].join("/") || "未记录";
    const keyOf = (message: ChatMessage) => JSON.stringify([message.model, message.reasoning, reasoning(message), message.modelTimings?.[0]?.transport, inputBand(message), turnCount(message), message.contextUsage?.windowTokens, message.contextUsage?.reservedOutputTokens]);
    const variants = [...new Set(completed.map(keyOf))].map((key) => {
      const group = completed.filter((message) => keyOf(message) === key);
      const turns = group.flatMap((message) => message.modelTimings ?? []);
      return { submittedReasoning: reasoning(group[0]!), inputBand: inputBand(group[0]!), turnsPerSample: turnCount(group[0]!), windowTokens: group[0]!.contextUsage?.windowTokens, reserveOutputTokens: group[0]!.contextUsage?.reservedOutputTokens, model: group[0]!.model ?? "未记录", reasoning: group[0]!.reasoning ?? "未记录", transport: turns[0]?.transport ?? "未记录", samples: group.length, firstTokenP50: percentile(group.map((message) => message.firstTokenMs), .5), inputTokens: group.reduce((sum, message) => sum + (message.usage?.inputTokens ?? 0), 0), outputTokens: group.reduce((sum, message) => sum + (message.usage?.outputTokens ?? 0), 0), cacheReadTokens: group.reduce((sum, message) => sum + (message.usage?.cacheReadTokens ?? 0), 0), startupP50: percentile(turns.map((turn) => turn.startupMs), .5), measuredTurns: turns.length, requestP50: percentile(turns.map((turn) => turn.requestMs), .5), firstEventP50: percentile(turns.map((turn) => turn.firstEventMs), .5), processTailP50: percentile(turns.map((turn) => turn.processTailMs), .5) };
    });
    return { provider, variants, completed: completed.length, failed: samples.filter((message) => message.status === "failed").length, interrupted: samples.filter((message) => message.status === "interrupted").length, firstTokenP50: percentile(completed.map((message) => message.firstTokenMs), .5), firstTokenP95: percentile(completed.map((message) => message.firstTokenMs), .95), durationP50: percentile(completed.map((message) => message.durationMs), .5), contextP50: percentile(completed.map((message) => message.timings?.contextMs), .5), modelP50: percentile(completed.map((message) => message.timings?.modelMs), .5), compactionP50: percentile(completed.map((message) => message.timings?.compactionMs), .5) };
  });
}
